### ISSUE TITLE
kubelet restart takes RDMA plugin interfaces offline - should be transparent?

### ISSUE THREAD

**Issue by hassanbabaie** [Mellanox/k8s-rdma-shared-dev-plugin#118]
We've tested on a number of releases but still hit the issue.

When leveraging the k8s-rdma-shared-dev-plugin (v1.5.1) a kubelet restart which happens for various reasons will take the interfaces offline for the pod that is using them. This is normally a transparent activity

We thought this was a timing issue but even when we set the periodicUpdateInterval high so that it is not polling frequently the issue still occurs.

Example messages the plugin reports during a kubelet restart:

```
2024/10/29 03:13:00 warning: server endpoint not found hca_shared_devices_b.sock
2024/10/29 03:13:00 warning: most likely Kubelet restarted
2024/10/29 03:13:00 restarting rdma/hca_shared_devices_b device plugin server...
2024/10/29 03:13:00 warning: server endpoint not found hca_shared_devices_d.sock
2024/10/29 03:13:00 warning: most likely Kubelet restarted
2024/10/29 03:13:00 restarting rdma/hca_shared_devices_d device plugin server...
2024/10/29 03:13:00 warning: server endpoint not found hca_shared_devices_a.sock
2024/10/29 03:13:00 warning: most likely Kubelet restarted
```

Is this expected behavior?

**Comment by adrianchiris** [comment]
i would expect device plugin to recover if kubelet restart.

**Comment by hassanbabaie** [comment]
Thanks for the quick reply @adrianchiris,

yes the plugin recovers however this recovery process interrupts the interfaces that are in use by a pod and so kills the current training process/job

As far as I can tell we don't see this issue with any other passed through resource including the GPUs so I'm wondering if this is expected?

**Comment by adrianchiris** [comment]
what is the interruption ? how does the interface interruption manifest ?

rdma-shared-device-plugin just discovers the resources according to provided configuration it does not "(or should not)  do anything that might affect the devices it discovers and allocates

**Comment by adrianchiris** [comment]
id say it correlates with kubelet restart. lets try to isolate the problem a bit more.

could you try using ib_write_bw and just running rdma traffic between two pods ? then restart kubelet ?
in this case is traffic still failing. id like to isolate to just rdma traffic and not model training.

ib_write_bw can be found as part of `perftest` package which can be installed in a container with common package manager.

e.g : `apt-get install perftest`

**Comment by hassanbabaie** [comment]
Thanks @adrianchiris for this information, we also found some of out older servers did not have this issue. We're sense checking our CNI plugin to see if this is messing with it due to recent updates.

I will update here hopefully next week

**Comment by hassanbabaie** [comment]
Hi @adrianchiris just to close this one out,

There was a regression in how the v1.25.16 kubelet treated pod attached resources during a restart, see: https://github.com/kubernetes/kubernetes/issues/118559 for more info.

We have moved back to an even older one (for now) v1.24.16 and this appears to have resolved the issue.

Thank you for your quick responses
