### ISSUE TITLE
The plugin doesn't fail when the net device doesn't exist

### ISSUE THREAD

**Issue by Mmduh-483** [Mellanox/k8s-rdma-shared-dev-plugin#4]
**Current Behavior:**
When pass a config like:
```
    {"configList": [{
             "resourceName": "hca_shared_devices_a",
             "rdmaHcaMax": 1000,
             "devices": ["ib0", "ib1","ib99"]
           }]}
```
and the device `ib99` doesn't exist in the host then plugin just skip it without failing.

**Expected Behavior:**
The plugin should fail if there is any missing device.

**Comment by adrianchiris** [comment]
IMO it should log an error and create the resource with 0 resources if a device doesnt exist.

**Comment by vtlrazin** [comment]
I endorse, with the wrong configuration the plugin should not create a resource or create the resource with 0.
