### ISSUE TITLE
Plugin always exposes RdmaHcaMax devices?

### ISSUE THREAD

**Issue by crd477** [Mellanox/k8s-rdma-shared-dev-plugin#44]
I have a mix of host configurations, some with 8x IB HCA, and one with 1x IB HCA.

My goal was for users not to have to apply a special case per host type, only request `rdma/hca: n`, so I supplied the following configuration:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: rdma-devices
  namespace: kube-system
data:
  config.json: |
    {
        "periodicUpdateInterval": 300,
        "configList": [{
             "resourceName": "hca",
             "rdmaHcaMax": 8,
             "selectors": {
               "linkTypes": ["infiniband"]
             }
           }
        ]
    }
```

On the host with only 1x IB HCA, I still see:
```
$ kubectl logs pod/rdma-shared-dp-ds-th298 -n kube-system|tail
2021/10/29 13:16:23 discovering host network devices
2021/10/29 13:16:23 DiscoverHostDevices(): device found: 0000:61:00.0   02              Intel Corporation       Ethernet Controller 10G X550T
2021/10/29 13:16:23 DiscoverHostDevices(): device found: 0000:61:00.1   02              Intel Corporation       Ethernet Controller 10G X550T
2021/10/29 13:16:23 DiscoverHostDevices(): device found: 0000:a1:00.0   02              Mellanox Technolo...    MT28908 Family [ConnectX-6]
2021/10/29 13:16:23 DiscoverHostDevices(): device found: 0000:e1:00.0   02              Mellanox Technolo...    MT28908 Family [ConnectX-6]
2021/10/29 13:16:23 error creating new device: "missing RDMA device spec for device 0000:61:00.0, RDMA device \"issm\" not found"
2021/10/29 13:16:23 error creating new device: "missing RDMA device spec for device 0000:61:00.1, RDMA device \"issm\" not found"
2021/10/29 13:16:23 no changes to devices for "rdma/hca"
2021/10/29 13:16:23 exposing "8" devices
```
(Note: only one of those 2 ConnectX-6 devices is configured for IB.)  Shouldn't that only be 1 exposed device?

The hosts that physically have 8x HCA work as intended.
Apologies in advance if I've simply misinterpreted how things are meant to work.

**Comment by adrianchiris** [comment]
Hi, `rdmaHcaMax` is an arbitrary number that is used to report to kubelet the amount of resources.
essentially, as this device plugin "shares" the RDMA resources, it is used to limit the amount of workloads that consume this resource.

in your configuration above, the `hca` resource will consist of all NICs with link type infiniband (that support RDMA ofc)

**Comment by adrianchiris** [comment]
closing due to in activity.

**Comment by Enjia** [comment]
I met the same errors as below, how do you solve this problem? Thanks @crd477 
2023/09/02 06:23:37 periodic update interval: +300
2023/09/02 06:23:37 Discovering host devices
2023/09/02 06:23:37 discovering host network devices
2023/09/02 06:23:37 DiscoverHostDevices(): device found: 0000:2e:00.0   02              Mellanox Technolo...    MT27800 Family [ConnectX-5] 
2023/09/02 06:23:37 DiscoverHostDevices(): device found: 0000:2f:00.0   02              Mellanox Technolo...    MT27800 Family [ConnectX-5] 
2023/09/02 06:23:37 DiscoverHostDevices(): device found: 0000:45:00.0   02              Intel Corporation       Ethernet Controller X710 for 10GbE SFP+
2023/09/02 06:23:37 DiscoverHostDevices(): device found: 0000:45:00.1   02              Intel Corporation       Ethernet Controller X710 for 10GbE SFP+
2023/09/02 06:23:37 DiscoverHostDevices(): device found: 0000:6c:00.0   02              Mellanox Technolo...    MT27800 Family [ConnectX-5] 
2023/09/02 06:23:37 DiscoverHostDevices(): device found: 0000:6d:00.0   02              Mellanox Technolo...    MT27800 Family [ConnectX-5] 
2023/09/02 06:23:37 DiscoverHostDevices(): device found: 0000:a8:00.0   02              Mellanox Technolo...    MT27800 Family [ConnectX-5] 
2023/09/02 06:23:37 DiscoverHostDevices(): device found: 0000:a9:00.0   02              Mellanox Technolo...    MT27800 Family [ConnectX-5] 
2023/09/02 06:23:37 DiscoverHostDevices(): device found: 0000:bf:00.0   02              Mellanox Technolo...    MT27710 Family [ConnectX-4 Lx]
2023/09/02 06:23:37 DiscoverHostDevices(): device found: 0000:bf:00.1   02              Mellanox Technolo...    MT27710 Family [ConnectX-4 Lx]
2023/09/02 06:23:37 DiscoverHostDevices(): device found: 0000:eb:00.0   02              Mellanox Technolo...    MT27800 Family [ConnectX-5] 
2023/09/02 06:23:37 DiscoverHostDevices(): device found: 0000:ec:00.0   02              Mellanox Technolo...    MT27800 Family [ConnectX-5] 
2023/09/02 06:23:37 Initializing resource servers
2023/09/02 06:23:37 Resource: &{ResourceName:hpc_shared_devices_a ResourcePrefix:rdma RdmaHcaMax:1000 Devices:[] Selectors:{Vendors:[15b3] DeviceIDs:[1017] Drivers:[] IfNames:[ens11np0] LinkTypes:[]}}
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:2e:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:2f:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:45:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:45:00.1, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:6c:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:6d:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:a8:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:a9:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:bf:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:bf:00.1, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:eb:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:ec:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 Warning: no devices in device pool, creating empty resource server for hpc_shared_devices_a
2023/09/02 06:23:37 Warning: no Rdma Devices were found for resource hpc_shared_devices_a
2023/09/02 06:23:37 Resource: &{ResourceName:hpc_shared_devices_b ResourcePrefix:rdma RdmaHcaMax:1000 Devices:[] Selectors:{Vendors:[15b3] DeviceIDs:[1017] Drivers:[] IfNames:[ens12np0] LinkTypes:[]}}
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:2e:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:2f:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:45:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:45:00.1, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:6c:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:6d:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:a8:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:a9:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:bf:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:bf:00.1, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:eb:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:ec:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 Warning: no devices in device pool, creating empty resource server for hpc_shared_devices_b
2023/09/02 06:23:37 Warning: no Rdma Devices were found for resource hpc_shared_devices_b
2023/09/02 06:23:37 Resource: &{ResourceName:hpc_shared_devices_c ResourcePrefix:rdma RdmaHcaMax:1000 Devices:[] Selectors:{Vendors:[15b3] DeviceIDs:[1017] Drivers:[] IfNames:[ens13np0] LinkTypes:[]}}
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:2e:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:2f:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:45:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:45:00.1, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:6c:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:6d:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:a8:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:a9:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:bf:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:bf:00.1, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:eb:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:ec:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 Warning: no devices in device pool, creating empty resource server for hpc_shared_devices_c
2023/09/02 06:23:37 Warning: no Rdma Devices were found for resource hpc_shared_devices_c
2023/09/02 06:23:37 Resource: &{ResourceName:hpc_shared_devices_d ResourcePrefix:rdma RdmaHcaMax:1000 Devices:[] Selectors:{Vendors:[15b3] DeviceIDs:[1017] Drivers:[] IfNames:[ens14np0] LinkTypes:[]}}
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:2e:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:2f:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:45:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:45:00.1, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:6c:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:6d:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:a8:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:a9:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:bf:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:bf:00.1, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:eb:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:ec:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 Warning: no devices in device pool, creating empty resource server for hpc_shared_devices_d
2023/09/02 06:23:37 Warning: no Rdma Devices were found for resource hpc_shared_devices_d
2023/09/02 06:23:37 Resource: &{ResourceName:hpc_shared_devices_e ResourcePrefix:rdma RdmaHcaMax:1000 Devices:[] Selectors:{Vendors:[15b3] DeviceIDs:[1017] Drivers:[] IfNames:[ens15np0] LinkTypes:[]}}
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:2e:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:2f:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:45:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:45:00.1, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:6c:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:6d:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:a8:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:a9:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:bf:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:bf:00.1, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:eb:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:ec:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 Warning: no devices in device pool, creating empty resource server for hpc_shared_devices_e
2023/09/02 06:23:37 Warning: no Rdma Devices were found for resource hpc_shared_devices_e
2023/09/02 06:23:37 Resource: &{ResourceName:hpc_shared_devices_f ResourcePrefix:rdma RdmaHcaMax:1000 Devices:[] Selectors:{Vendors:[15b3] DeviceIDs:[1017] Drivers:[] IfNames:[ens16np0] LinkTypes:[]}}
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:2e:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:2f:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:45:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:45:00.1, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:6c:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:6d:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:a8:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:a9:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:bf:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:bf:00.1, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:eb:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:ec:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 Warning: no devices in device pool, creating empty resource server for hpc_shared_devices_f
2023/09/02 06:23:37 Warning: no Rdma Devices were found for resource hpc_shared_devices_f
2023/09/02 06:23:37 Resource: &{ResourceName:hpc_shared_devices_g ResourcePrefix:rdma RdmaHcaMax:1000 Devices:[] Selectors:{Vendors:[15b3] DeviceIDs:[1017] Drivers:[] IfNames:[ens17np0] LinkTypes:[]}}
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:2e:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:2f:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:45:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:45:00.1, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:6c:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:6d:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:a8:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:a9:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:bf:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:bf:00.1, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:eb:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:ec:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 Warning: no devices in device pool, creating empty resource server for hpc_shared_devices_g
2023/09/02 06:23:37 Warning: no Rdma Devices were found for resource hpc_shared_devices_g
2023/09/02 06:23:37 Resource: &{ResourceName:hpc_shared_devices_h ResourcePrefix:rdma RdmaHcaMax:1000 Devices:[] Selectors:{Vendors:[15b3] DeviceIDs:[1017] Drivers:[] IfNames:[ens18np0] LinkTypes:[]}}
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:2e:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:2f:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:45:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:45:00.1, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:6c:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:6d:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:a8:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:a9:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:bf:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:bf:00.1, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:eb:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 error creating new device: "missing RDMA device spec for device 0000:ec:00.0, RDMA device \"issm\" not found"
2023/09/02 06:23:37 Warning: no devices in device pool, creating empty resource server for hpc_shared_devices_h
2023/09/02 06:23:37 Warning: no Rdma Devices were found for resource hpc_shared_devices_h

**Comment by adrianchiris** [comment]
@Enjia this is not the same  issue.

in the original  issue the "RDMA device  issm not found" is emitted for intel NICs.

in your case we see that some RDMA char devices are missing from the system (mainly /dev/infiniband/issm<N>
please make sure you have rdma-core package installed.

**Comment by Enjia** [comment]
@adrianchiris Thanks for your help. RDMA-core has been installed actually and I checked directory (that is "ll /dev/infiniband/") and found issms have already existed: 
total 0
drwxr-xr-x  2 root root      660 9月   4 14:50 ./
drwxr-xr-x 21 root root     5480 9月   4 14:53 ../
crw-------  1 root root 231,  64 9月   4 14:50 issm0
crw-------  1 root root 231,  65 9月   4 14:50 issm1
crw-------  1 root root 231,  66 9月   4 14:50 issm2
crw-------  1 root root 231,  67 9月   4 14:50 issm3
crw-------  1 root root 231,  68 9月   4 14:50 issm4
crw-------  1 root root 231,  69 9月   4 14:50 issm5
crw-------  1 root root 231,  70 9月   4 14:50 issm6
crw-------  1 root root 231,  71 9月   4 14:50 issm7
crw-------  1 root root 231,  72 9月   4 14:50 issm8
crw-------  1 root root 231,  73 9月   4 14:50 issm9
crw-rw-rw-  1 root root  10, 121 9月   4 14:50 rdma_cm
crw-------  1 root root 231,   0 9月   4 14:50 umad0
crw-------  1 root root 231,   1 9月   4 14:50 umad1
crw-------  1 root root 231,   2 9月   4 14:50 umad2
crw-------  1 root root 231,   3 9月   4 14:50 umad3
crw-------  1 root root 231,   4 9月   4 14:50 umad4
crw-------  1 root root 231,   5 9月   4 14:50 umad5
crw-------  1 root root 231,   6 9月   4 14:50 umad6
crw-------  1 root root 231,   7 9月   4 14:50 umad7
crw-------  1 root root 231,   8 9月   4 14:50 umad8
crw-------  1 root root 231,   9 9月   4 14:50 umad9
crw-rw-rw-  1 root root 231, 192 9月   4 14:50 uverbs0
crw-rw-rw-  1 root root 231, 193 9月   4 14:50 uverbs1
crw-rw-rw-  1 root root 231, 194 9月   4 14:50 uverbs2
crw-rw-rw-  1 root root 231, 195 9月   4 14:50 uverbs3
crw-rw-rw-  1 root root 231, 196 9月   4 14:50 uverbs4
crw-rw-rw-  1 root root 231, 197 9月   4 14:50 uverbs5
crw-rw-rw-  1 root root 231, 198 9月   4 14:50 uverbs6
crw-rw-rw-  1 root root 231, 199 9月   4 14:50 uverbs7
crw-rw-rw-  1 root root 231, 200 9月   4 14:50 uverbs8
crw-rw-rw-  1 root root 231, 201 9月   4 14:50 uverbs9

It seems that the device plugin hasn't found these issms yet? FIY I use the latest k8s-rdma-shared-dev-plugin-ds.yaml as well as configmap provided by this repository.

**Comment by Enjia** [comment]
@adrianchiris Thank for your advice! I figured it out and the reason is I forgot to run "/etc/init.d/openibd restart" which led to the missing of issm in worker node.
