### ISSUE TITLE
Docker build failed for reason: "make: /bin/sh: Operation not permitted"

### ISSUE THREAD

**Issue by miaojianwei** [Mellanox/k8s-rdma-shared-dev-plugin#49]
**Logs**

> root@3C6DBT2 ~/m/k8s-rdma-shared-dev-plugin (master) [2]# docker build -t k8s-rdma-shared-dev-plugin --build-arg BASE_IMAGE=registry.access.redhat.com/ubi8/ubi-minimal:latest .
Sending build context to Docker daemon  5.705MB
Step 1/11 : ARG BASE_IMAGE=alpine:3.14.3
Step 2/11 : FROM golang:alpine as builder
 ---> d8bf44a3f6b4
...
Step 6/11 : RUN apk add --update --virtual build-dependencies build-base linux-headers git &&     cd /usr/src/k8s-rdma-shared-dp &&     make clean &&     make build
...
(28/28) Installing build-dependencies (20220119.055023)
Executing busybox-1.34.1-r3.trigger
OK: 217 MiB in 43 packages
make: /bin/sh: Operation not permitted
Cleaning...
make: /bin/sh: Operation not permitted
make: *** [Makefile:120: clean] Error 127
The command '/bin/sh -c apk add --update --virtual build-dependencies build-base linux-headers git &&     cd /usr/src/k8s-rdma-shared-dp &&     make clean &&     make build' returned a non-zero code: 2 

**Versions**
device plugin: master
docker: 

> Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:56 2018
 OS/Arch:           linux/amd64
 Experimental:      false

> Server:
>  Engine:
>   Version:          18.06.1-ce
>   API version:      1.38 (minimum version 1.12)
>   Go version:       go1.10.3
>   Git commit:       e68fc7a
>   Built:            Tue Aug 21 17:23:21 2018
>   OS/Arch:          linux/amd64
>   Experimental:     false

**PR**
The reason is https://github.com/docker-library/php/issues/1177
I submit a PR to resolve this. #47

**Comment by e0ne** [comment]
@miaojianwei  I can reproduce this on my local env. Here is logs for Alpine-based image https://paste.openstack.org/show/812273/ and UBI-based image https://paste.openstack.org/show/812274/

**Comment by miaojianwei** [comment]
@e0ne It is related to docker version. Upgrading the docker is also a solution, or it would be better to change the golang:alpine version？

**Comment by e0ne** [comment]
@miaojianwei  I don't want to downgrade base image version. I prefer keep it up-to-date to have lates stability, performance and security fixes.

@adrianchiris do you have any thoughts on this?

**Comment by miaojianwei** [comment]
@e0ne I agree with you that fixing to an old version is not a good idea, so we can close the issue.

If anyone  have the same problem, the solution is:
1. Upgrade docker to upgrade Docker to version 20.10.0 or later as per [Alpine 3.14.0 Release Notes](https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.14.0#faccessat2)
2. Or modify the image used for compile code from `golang: alpine` to `golang: Alpine3.13` in the Dockerfile in your own development environment

**Comment by adrianchiris** [comment]
IMO we should avoid downgrading alpine. we should add a README note on this limitation

**Comment by adrianchiris** [comment]
#50
