### ISSUE TITLE
Do we need to reconfigure CNI plugin before deploying rdma-plugin

### ISSUE THREAD

**Issue by Binyang2014** [Mellanox/k8s-rdma-shared-dev-plugin#53]
From the doc it said: `Make sure to configure ib0 or appropriate IPoIB netdevice as the parent netdevice for creating overlay/virtual netdevices.`
I am not sure what's the meaning for this sentence. We use `Calico` cni, do we need to change some config before using `rdma-shared-dev-plugin`?

And what's the difference for `How to use device plugin` and `How to use device plugin for RDMA`? For the second section, These is some config change for `macvlan cni`, but I don't known the purpose for this change

**Comment by adrianchiris** [comment]
Hi there,

going over the README, i think it could use some updates/improvements.

to address your questions:

> I am not sure what's the meaning for this sentence. We use Calico cni, do we need to change some config before using rdma-shared-dev-plugin?

`ib0 or appropriate IPoIB netdevice` is for use-cases where the underlying fabric used is infiniband. if this is not the case for you then you can disregard.

i have no experience with using calico as primary network + sending RDMA over the same network.

The general recommendation is to use a k8s secondary network for RDMA with CNI such as macvlan (eth), or ipoib (infiniband)

> And what's the difference for How to use device plugin and How to use device plugin for RDMA?

the former demonstrates (basic) steps how to deploy device plugin. The latter shows an example of how to use RDMA device plugin in conjunction with macvlan CNI.

**Comment by Binyang2014** [comment]
Thanks @adrianchiris. We need to run some MPI applications which use IB for multi-nodes communication. 

Since MPI just using OFED and doesn't need IPoIB, so seems we don't need to care about CNI. We can install the device plugin then claim the required resource in POD spec. Then everything will be ok. Am I correct?

**Comment by adrianchiris** [comment]
if you dont need to use RDMA_CM then you should be OK with just device plugin.

**Comment by adrianchiris** [comment]
closing issue as no more open questions in this thread.

**Comment by Kyrie336** [comment]
@Binyang2014 Hello, did you successfully experiment with using only rdma device plugin in pod instead of a secondary Network like macvlan? I've seen a lot of examples, and they usually combine the macvlan with the rdma device plugin.
