### ISSUE TITLE
Unable to Connect the HCA's through the link

### ISSUE THREAD

**Issue by heshengkai** [Mellanox/k8s-rdma-shared-dev-plugin#72]
I deployed the rdma device plugin in HCA mode in kubernetes cluster. When I tried to make a connection test using "ib_read_bw", the output is as follows:
                    RDMA_Write BW Test
 Dual-port       : OFF          Device         : mlx5_2
 Number of qps   : 1            Transport type : IB
 Connection type : RC           Using SRQ      : OFF
 TX depth        : 128
 CQ Moderation   : 100
 Mtu             : 1024[B]
 Link type       : Ethernet
 GID index       : 0
 Max inline data : 0[B]
 rdma_cm QPs     : OFF
 Data ex. method : Ethernet
---------------------------------------------------------------------------------------
 local address: LID 0000 QPN 0x003b PSN 0xab3a5e RKey 0x015b1a VAddr 0x007f72e9620000
 GID: 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
 remote address: LID 0000 QPN 0x003c PSN 0x65b096 RKey 0x014d0c VAddr 0x007fcb322d5000
 GID: 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
Failed to modify QP 59 to RTR
 Unable to Connect the HCA's through the link

The commands I used are simply ' ib_write_bw -d mlx5_0 [target_ip]' and 'ib_read_bw -d mlx5_0
'. Could anyone please help with this issue? I appreciate your help.

**Comment by adrianchiris** [comment]
HI,

what is the output of `/dev/infiniband` in container ? 

i see link type is ethernet, are you using macvlan as secondary network ? 
your GIDs are zero so RoCE will not work,

**Comment by heshengkai** [comment]
root@192-168-0-200:/home/sunwisehk/hesk1/k8s-rdma-shared-dev-plugin-1.3.2/example# kubectl logs -f  mofed-test-pod-t
/dev/infiniband:
total 0
crw------- 1 root root 231,  66 Apr 20 12:42 issm2
crw-rw-rw- 1 root root  10, 120 Apr 20 12:42 rdma_cm
crw------- 1 root root 231,   2 Apr 20 12:42 umad2
crw-rw-rw- 1 root root 231, 194 Apr 20 12:42 uverbs2

/sys/class/infiniband:
total 0
lrwxrwxrwx 1 root root 0 Apr 20 12:42 mlx5_0 -> ../../devices/pci0000:16/0000:16:02.0/0000:17:00.0/infiniband/mlx5_0
lrwxrwxrwx 1 root root 0 Apr 20 12:42 mlx5_1 -> ../../devices/pci0000:16/0000:16:02.0/0000:17:00.1/infiniband/mlx5_1
lrwxrwxrwx 1 root root 0 Apr 20 12:42 mlx5_2 -> ../../devices/pci0000:64/0000:64:02.0/0000:65:00.0/infiniband/mlx5_2
lrwxrwxrwx 1 root root 0 Apr 20 12:42 mlx5_3 -> ../../devices/pci0000:97/0000:97:02.0/0000:98:00.0/infiniband/mlx5_3
lrwxrwxrwx 1 root root 0 Apr 20 12:42 mlx5_4 -> ../../devices/pci0000:97/0000:97:02.0/0000:98:00.1/infiniband/mlx5_4
lrwxrwxrwx 1 root root 0 Apr 20 12:42 mlx5_5 -> ../../devices/pci0000:c9/0000:c9:02.0/0000:ca:00.0/infiniband/mlx5_5
lrwxrwxrwx 1 root root 0 Apr 20 12:42 mlx5_6 -> ../../devices/pci0000:c9/0000:c9:02.0/0000:ca:00.1/infiniband/mlx5_6

/sys/class/net:
total 0
lrwxrwxrwx 1 root root 0 Apr 20 12:42 eth0 -> ../../devices/virtual/net/eth0
lrwxrwxrwx 1 root root 0 Apr 20 12:42 lo -> ../../devices/virtual/net/lo
lrwxrwxrwx 1 root root 0 Apr 20 12:42 tunl0 -> ../../devices/virtual/net/tunl0

**Comment by heshengkai** [comment]
[root@mofed-test-pod-t /]# ib_write_bw -d mlx5_2  -F  --report_gbits 172.16.62.139 --gid-index=6
---------------------------------------------------------------------------------------
                    RDMA_Write BW Test
 Dual-port       : OFF          Device         : mlx5_2
 Number of qps   : 1            Transport type : IB
 Connection type : RC           Using SRQ      : OFF
 TX depth        : 128
 CQ Moderation   : 100
 Mtu             : 1024[B]
 Link type       : Ethernet
 GID index       : 6
 Max inline data : 0[B]
 rdma_cm QPs     : OFF
 Data ex. method : Ethernet
---------------------------------------------------------------------------------------
 local address: LID 0000 QPN 0x003e PSN 0x660573 RKey 0x017536 VAddr 0x007ff12aaf6000
 GID: 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
 remote address: LID 0000 QPN 0x003d PSN 0x67ec97 RKey 0x016929 VAddr 0x007f26b943e000
 GID: 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
Failed to modify QP 62 to RTR
 Unable to Connect the HCA's through the link

**Comment by heshengkai** [comment]
There is no problem using macvlan as a secondary network, but   be able to use secondary network  for my scene, Only calico is used

**Comment by adrianchiris** [comment]
So, pod has only a single network (the primary one) which is calico right ?

Im not sure it can work for ethernet fabric like this.

device plugin did its job of mounting RDMA char devs to container under `/dev/infiniband`

**Comment by heshengkai** [comment]
yes， pod has only a single network (the primary one) which is calico。

**Comment by heshengkai** [comment]
my test results:
     Link type is IB, and the cni is calico or macvlan. Both work properly。
     Link type is Ethernet, cni is calico, the test is abnormal. cni is macvlan and the test is normal

**Comment by adrianchiris** [comment]
@heshengkai, the fact that it doesnt work with calico in ETH is IMO not related to device plugin.

my recommendation is to use macvlan as a secondary network so that in container, kernel can associate netdev with RDMA device to allow RoCE to work.

**Comment by heshengkai** [comment]
@adrianchiris Thank you for your reply. I will use it according to your recommendation

**Comment by adrianchiris** [comment]
closing this issue. please re-open if problem persists with macvlan.
