### ISSUE TITLE
Exiting.. can not change : incorrect RDMA subsystem network namespace

### ISSUE THREAD

**Issue by foursunZero** [Mellanox/k8s-rdma-shared-dev-plugin#84]
error message as follows
```
2023/09/08 17:43:19 Starting K8s RDMA Shared Device Plugin version= master
2023/09/08 17:43:19 resource manager reading configs
2023/09/08 17:43:19 Reading /k8s-rdma-shared-dev-plugin/config.json
Using Kubelet Plugin Registry Mode
2023/09/08 17:43:19 loaded config: [{ResourceName:rdma_share RdmaHcaMax:1000 Devices:[] Selectors:{Vendors:[] DeviceIDs:[] Drivers:[mlx5_core] IfNames:[] LinkTypes:[]}}] 
2023/09/08 17:43:19 periodic update interval: +300 
2023/09/08 17:43:19 Exiting.. can not change : incorrect RDMA subsystem network namespace
```
I have no clue about this error, can anyone give some advice ？

**Comment by adrianchiris** [comment]
this error originates here; https://github.com/Mellanox/k8s-rdma-shared-dev-plugin/blob/b3d2b2a1c52701afc1fd4e1bd3ee9f4f7b1a9dc7/pkg/resources/resources_manager.go#L174

it seems your OS is configured with rdma namespace set to exclusive instead of shared.

**Comment by foursunZero** [comment]
> this error originates here;
> 
> https://github.com/Mellanox/k8s-rdma-shared-dev-plugin/blob/b3d2b2a1c52701afc1fd4e1bd3ee9f4f7b1a9dc7/pkg/resources/resources_manager.go#L174
> 
> it seems your OS is configured with rdma namespace set to exclusive instead of shared.

Emm, I think so. But when I use `rdma` command, it happens some error as follow. Any other advice,thanks
```
$ rdma system show
Unknown object 'system'.
```

**Comment by adrianchiris** [comment]
hmm, it works on my setup:

```
# rdma system
netns shared copy-on-fork on
```

what kernel are you using ? maybe you need to update iproute2 package ?

**Comment by foursunZero** [comment]
> hmm, it works on my setup:
> 
> ```
> # rdma system
> netns shared copy-on-fork on
> ```
> 
> what kernel are you using ? maybe you need to update iproute2 package ?

 It is my kernel and iproute2 package information as follows. I coundn't comfirm they were the proper version
 ```
$ rpm -qa |grep iproute
mlnx-iproute2-5.6.0-1.51258.x86_64
iproute-4.11.0-30.el7.x86_64
$ uname -r
3.10.0-1160.el7.x86_64
```
and it is centos7.9 OS

**Comment by adrianchiris** [comment]
Its an old kernel, which MLNX OFED version are you using ?

**Comment by foursunZero** [comment]
> Its an old kernel, which MLNX OFED version are you using ? if you do use MLNX OFED can you try running rdma tool from /opt/mellanox/bin/rdma ? (you should have rdma binary part of mlnx-iproute2 package)
> 
> the device plugin uses netlink go lib to query rdma system mode, it seems to return your system is configured in exclusive mode.

Thanks, I got it. I use mlnx-iproute2 package to configuare the rdma system mode and got some error.
```
$ /opt/mellanox/iproute2/sbin/rdma system set netns shared 
error: Device or resource busy
```
I try to stop openibd service and reboot the machine,but it still has no effect. How can I stop the device properly so that I can configuare the rdma system mode
