### ISSUE TITLE
can't work in ROCE v2

### ISSUE THREAD

**Issue by zzhint** [Mellanox/k8s-rdma-shared-dev-plugin#86]
Hello, when I use this plugin, I found that nics in different network segments cannot communicate, I think it is because I didn't use roce v2, but even I change the gid index (which show in show_gids), it didn't work too, can I have your help?

**Comment by adrianchiris** [comment]
is there a specific issue with k8s-rdma-shared-dev-plugin ?

it seems like system / fabric configurations.

**Comment by adrianchiris** [comment]
can you provide your full k8s config ?

- rdma shared device plugin config
-  rdma shared device plugin logs
- pod object
- network attachment definition
- output of `ip a show`, `ip link show` in both pods
- content of /dev/infiniband folder of workload container in both pods

**Comment by zzhint** [comment]
I am sorry, we have changed the cni, now it works

**Comment by haswelliris** [comment]
@zzhint What cni did you use? I may meet the same problem with you that ib_write_bw just not work(no such device). Could you share what CNI you finally use and general configs?
