### ISSUE TITLE
When netns is set to exclusive mode, rdma-shared-dp-ds will not start

### ISSUE THREAD

**Issue by peterwi** [Mellanox/k8s-rdma-shared-dev-plugin#87]
If I set netns mode to exclusive, I get 
rdma-shared-dp-ds CrashLoopBackOff

`kubectl logs rdma-shared-dp-ds-8sd7z -n nvidia-network-operator -c rdma-shared-dp`

` Exiting.. can not change : incorrect RDMA subsystem network namespace`

How can I enable exclusive mode to allow network namespace isolation for RDMA workloads?

**Comment by adrianchiris** [comment]
if you chose to isolate RDMA device via network namespace, how can you expect to share it across workloads ?
this is an unsupported configuration for this device plugin hence the check (and error).
