### ISSUE TITLE
how to delete rdma device from kubelet

### ISSUE THREAD

**Issue by 47oo** [Mellanox/k8s-rdma-shared-dev-plugin#90]
I changed  ib device name,but the old name still on node when I use kubectl describe node nodeXX and the resource can not use for value 0,I want to delete old name on kubelet node,how can i do?

**Comment by adrianchiris** [comment]
if you changed resource name then the old name remains on node, to remove it you can edit node obj and remove stale resource.
im not aware of any kubelet mechanism that removes such resources from node.
